[package]
edition      = "2024"
license      = "MIT"
name         = "cardputer-rust"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "cardputer-rust"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32s3", "log-04", "unstable"] }


esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3", "log-04"] }
log                    = "0.4.27"

critical-section = "1.2.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["esp32s3", "log-04"] }
embedded-graphics = "0.8.2"
embedded-hal = "1.0.0"
mipidsi = "0.10.0"
display-interface-spi = "0.5.0"
embedded-hal-bus = "0.3.0"
tca8418 = "0.2.2"
esp-radio = { version = "0.18.0", features = ["esp32s3", "wifi", "esp-alloc"] }
esp-rtos = { version = "0.3.0", features = ["esp32s3", "esp-radio", "esp-alloc", "embassy"] }
esp-alloc = { version = "0.10.0", features = ["esp32s3"] }
embassy-executor = { version = "0.10.0", default-features = false }
embassy-time = "0.5.1"
embassy-net = { version = "0.9.1", default-features = false, features = ["dhcpv4", "proto-ipv4", "medium-ethernet", "tcp"] }
embassy-futures = "0.1.2"


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
